apiVersion: apps/v1
kind: Deployment
metadata:
  name: amacconweb
  namespace: catclubsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amacconweb
  template:
    metadata:
      labels:
        app: amacconweb
    spec:
      serviceAccountName: amacoonwebccount
      containers:
      - name: amacconweb
        image: IMAGE_URL_PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
