apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amacconweb-hpa
  namespace: catclubsystem
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amacconweb
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
