apiVersion: v1
kind: Service
metadata:
  name: amacconweb
  namespace: catclubsystem
spec:
  selector:
    app: amacconweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer


  